# Project information
site_name: 'Computer Science Notes'
site_description: 'Computer Science Notes Operating System LeetCode Python Machine Learning'
site_author: 'Jay Chen'
site_url: 'https://walkccc.github.io/CS'

# Repository
repo_name: 'walkccc/CS'
repo_url: 'https://github.com/walkccc/CS'

# Copyright
copyright: 'Built by <a href="http://github.com/walkccc">Jay Chen</a> &copy; 2017 - 2019'

# Configuration
theme:
  name: 'material'
  language: 'en'
  custom_dir: 'custom/'
  favicon: 'assets/favicon.png'
  palette:
    primary: 'Indigo'
    accent: 'Blue'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  logo:
    icon: 'important_devices'
  feature:
    tabs: true

# Customization
extra:
  social:
    - type: 'github'
      link: 'https://github.com/walkccc'
    - type: 'quote-left'
      link: 'https://walkccc.github.io/blog'
    - type: 'book'
      link: 'https://walkccc.github.io/CLRS'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/in/jay-chen-57852313a'
    
extra_css:
  - 'css/katex.css'
  - 'css/style.css'

extra_javascript:
  - 'js/katex.js'
  - 'https://cdn.jsdelivr.net/npm/katex@0.10.0/dist/katex.min.js'
  - 'https://cdn.jsdelivr.net/npm/katex@0.10.0/dist/contrib/auto-render.min.js'

# Extensions
markdown_extensions:
  - pymdownx.superfences
  - admonition
  - toc:
      permalink: false
  - pymdownx.superfences

nav:
  - Preface: index.md
  - Operating System:
    - Preface: OS/index.md
    - PART ONE | OVERVIEW:
      - Chapter 1 Introduction: OS/Chap01.md
      - Chapter 2 Operating-System Structures: OS/Chap02.md
    - PART TWO | PROCESS MANAGEMENT:
      - Chapter 3 Processes: OS/Chap03.md
      - Chapter 4 Threads: OS/Chap04.md
      - Chapter 5 Process Synchronization: OS/Chap05.md
      - Chapter 6 CPU Scheduling: OS/Chap06.md
      - Chapter 7 Deadlocks: OS/Chap07.md
    - PART THREE | MEMORY MANAGEMENT:
      - Chapter 8 Main Memory: OS/Chap08.md
      - Chapter 9 Virtual Memory: OS/Chap09.md
    - Previous Exams: 
      - Midterm: OS/midterm.md
      - Final: OS/final.md
  - Machine Learning:
    - Preface: ML/index.md
    - Lec 1 - Regression - Case Study: ML/1.md
    - Lec 2 - Where does the error com from?: ML/2.md
    - Lec 3 - Gradient Descent: ML/3.md
    - Lec 4 - Classification: ML/4.md
    - Lec 5 - Logistic Regression: ML/5.md
    - Lec 6 - Deep Learning: ML/6.md
    - Lec 7 - Backpropagation: ML/7.md
    - 'Lec 8 - "Hello world" of Deep Learning': ML/8.md
    - Lec 9 - Tips for Deep Learning: ML/9.md
