# Project information
site_name: 'Computer Science Notes'
site_description: 'Computer Science Notes Operating System LeetCode Python Machine Learning'
site_author: 'Jay Chen'
site_url: 'https://walkccc.github.io/CS'

# Repository
repo_name: 'walkccc/CS'
repo_url: 'https://github.com/walkccc/CS'

# Copyright
copyright: 'Built by <a href="http://github.com/walkccc">Jay Chen</a> &copy; 2017 - 2019'

# Configuration
theme:
  name: 'material'
  language: 'en'
  custom_dir: 'custom/'
  favicon: 'assets/favicon.png'
  palette:
    primary: 'Indigo'
    accent: 'Blue'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  logo:
    icon: 'important_devices'
  feature:
    tabs: true

# Customization
extra:
  social:
    - type: 'github'
      link: 'https://github.com/walkccc'
    - type: 'quote-left'
      link: 'https://walkccc.github.io/blog'
    - type: 'book'
      link: 'https://walkccc.github.io/CLRS'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/in/jay-chen-57852313a'
    
extra_css:
  - 'css/katex.css'
  - 'https://cdn.jsdelivr.net/npm/katex@0.10.0/dist/katex.min.css'
  - 'css/style.css'

extra_javascript:
  - 'js/katex.js'
  - 'https://cdn.jsdelivr.net/npm/katex@0.10.0/dist/katex.min.js'
  - 'https://cdn.jsdelivr.net/npm/katex@0.10.0/dist/contrib/auto-render.min.js'

# Extensions
markdown_extensions:
  - pymdownx.superfences
  - admonition
  - toc:
      permalink: false
  - pymdownx.superfences

nav:
  - Preface: index.md
  - Operating System:
    - Preface: OS/index.md
    - PART ONE | OVERVIEW:
      - Chapter 1 Introduction: OS/Chap01.md
      - Chapter 2 Operating-System Structures: OS/Chap02.md
    - PART TWO | PROCESS MANAGEMENT:
      - Chapter 3 Processes: OS/Chap03.md
      - Chapter 4 Threads: OS/Chap04.md
      - Chapter 5 Process Synchronization: OS/Chap05.md
      - Chapter 6 CPU Scheduling: OS/Chap06.md
      - Chapter 7 Deadlocks: OS/Chap07.md
    - PART THREE | MEMORY MANAGEMENT:
      - Chapter 8 Main Memory: OS/Chap08.md
      - Chapter 9 Virtual Memory: OS/Chap09.md
    - Previous Exams: 
      - Midterm: OS/midterm.md
      - Final: OS/final.md
  - Machine Learning:
    - Preface: ML/index.md
    - Lec 1 - Regression - Case Study: ML/01.md
    - Lec 2 - Where does the error com from?: ML/02.md
    - Lec 3 - Gradient Descent: ML/03.md
    - Lec 4 - Classification: ML/04.md
    - Lec 5 - Logistic Regression: ML/05.md
    - Lec 6 - Deep Learning: ML/06.md
    - Lec 7 - Backpropagation: ML/07.md
    - 'Lec 8 - "Hello world" of Deep Learning': ML/08.md
    - Lec 9 - Tips for Deep Learning: ML/09.md
  - JavaScript DSA:
    - Preface: JavaScript/index.md
    - 01 - Problem Solving Patterns:
      - Frequency Counters: JavaScript/01/frequencyCounters.md
      - Multiple Pointers: JavaScript/01/multiplePointers.md
      - Sliding Window: JavaScript/01/slidingWindow.md
      - Divide and Conquer: JavaScript/01/divideAndConquer.md
    - 02 - Recursion Problem Set:
      - Recursion Problem Set (easy): JavaScript/02/recursionEasy.md
      - Recursion Problem Set (hard): JavaScript/02/recursionHard.md
    - 03 - Sorting Algorithms:
      - Bubble Sort: JavaScript/03/bubbleSort.md
      - Selection Sort: JavaScript/03/selectionSort.md
      - Insertion Sort: JavaScript/03/insertionSort.md
      - Merge Sort: JavaScript/03/mergeSort.md
      - Quick Sort: JavaScript/03/quickSort.md
    - 04 - Data Structures:
      - Singly Linked List: JavaScript/04/SinglyLinkedList.md
      - Doubly Linked List: JavaScript/04/DoublyLinkedList.md
      - Binary Search Tree: JavaScript/04/BinarySearchTree.md
      - Max Binary Heap: JavaScript/04/MaxBinaryHeap.md
      - Max Priority Queue: JavaScript/04/MaxPriorityQueue.md
    - 05 - Graphs:
      - Graph: JavaScript/05/Graph.md
      - Dijkstra Algorithm: JavaScript/05/Dijkstra.md

